import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const translations = {
  en: {
    appName: 'LogiRoute',
    tagline: 'Smart Logistics Optimizer',
    getStarted: 'Get Started',
    login: 'Login',
    register: 'Create Account',
    email: 'Email / Phone',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    welcome: 'Welcome Back 👋',
    loginSub: 'Login to your account',
    dashboard: 'Dashboard',
    shipments: 'Shipments',
    optimize: 'Optimize',
    analytics: 'Analytics',
    profile: 'Profile',
    newShipment: 'New Shipment',
    activeShipments: 'Active Shipments',
    trackLive: 'Track Live',
    bookTransport: 'Book Transport',
    payment: 'Payment',
    confirmed: 'Booking Confirmed!',
    weather: 'Weather',
    history: 'History',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Logout',
    source: 'Source city...',
    destination: 'Destination city...',
    optimizeRoute: '⚡ Optimize Route',
    material: 'Material',
    route: 'Route',
    distance: 'Distance',
    estTime: 'Est. Time',
    transport: 'Transport',
    minCost: 'MINIMUM COST',
    viewMap: '🗺 View Route Map',
    compareAll: '📊 Compare All Costs',
    bookThis: '✅ Book This Transport',
    driver: 'Driver',
    earnings: 'Earnings',
    myTrips: 'My Trips',
    jobs: 'Available Jobs',
    vehicle: 'Vehicle Status',
    goodMorning: 'Good Morning 👋',
    noAlerts: 'No weather alerts. Safe to dispatch.',
    selectMaterial: 'SELECT MATERIAL',
    proceed: 'Proceed to Pay',
    payNow: '🔒 Pay',
    back: '← Back',
    skip: 'Skip',
    next: 'Next →',
    chat: 'Chat',
    scanQR: 'Scan QR Code',
    offline: 'You are offline',
    offlineSub: 'Showing cached data',
    adminPanel: 'Admin Panel',
    
    // Profile menu items & badges
    editProfile: 'Edit Profile',
    companyDetails: 'Company Details',
    kycDocs: 'KYC & Vehicle Documents',
    paymentMethods: 'Payment Methods',
    notificationPrefs: 'Notification Preferences',
    helpSupport: 'Help & Support',
    aboutApp: 'About LogiRoute',
    driverLabel: 'Driver',
    companyLabel: 'Company',
    verifiedBadge: 'Verified',
    pendingBadge: 'Pending',
    editProfileSub: 'Update name, photo, contact',
    companyDetailsSub: 'GST, address, registration',
    kycDocsSub: 'Official PAN, Aadhaar, Vehicle RC',
    paymentMethodsSub: 'UPI, bank accounts',
  },
  ta: {
    appName: 'LogiRoute',
    tagline: 'ஸ்மார்ட் லாஜிஸ்டிக்ஸ் ஆப்டிமைசர்',
    getStarted: 'தொடங்கு',
    login: 'உள்நுழைய',
    register: 'கணக்கு உருவாக்கு',
    email: 'மின்னஞ்சல் / தொலைபேசி',
    password: 'கடவுச்சொல்',
    forgotPassword: 'கடவுச்சொல் மறந்தீர்களா?',
    welcome: 'மீண்டும் வருக 👋',
    loginSub: 'உங்கள் கணக்கில் உள்நுழைக்க',
    dashboard: 'டாஷ்போர்டு',
    shipments: 'ஏற்றுமதிகள்',
    optimize: 'உகந்தமாக்கு',
    analytics: 'பகுப்பாய்வு',
    profile: 'சுயவிவரம்',
    newShipment: 'புதிய ஏற்றுமதி',
    activeShipments: 'செயலில் உள்ள ஏற்றுமதிகள்',
    trackLive: 'நேரடி கண்காணிப்பு',
    bookTransport: 'போக்குவரத்து பதிவு',
    payment: 'கட்டணம்',
    confirmed: 'பதிவு உறுதிப்படுத்தப்பட்டது!',
    weather: 'வானிலை',
    history: 'வரலாறு',
    notifications: 'அறிவிப்புகள்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    source: 'மூல நகரம்...',
    destination: 'இலக்கு நகரம்...',
    optimizeRoute: '⚡ பாதையை உகந்தமாக்கு',
    material: 'பொருள்',
    route: 'பாதை',
    distance: 'தூரம்',
    estTime: 'மதிப்பிட்ட நேரம்',
    transport: 'போக்குவரத்து',
    minCost: 'குறைந்தபட்ச செலவு',
    viewMap: '🗺 வரைபடம் காண்',
    compareAll: '📊 அனைத்து செலவுகளை ஒப்பிடு',
    bookThis: '✅ இந்த போக்குவரத்தை பதிவு செய்',
    driver: 'ஓட்டுநர்',
    earnings: 'வருவாய்',
    myTrips: 'என் பயணங்கள்',
    jobs: 'கிடைக்கும் வேலைகள்',
    vehicle: 'வாகன நிலை',
    goodMorning: 'காலை வணக்கம் 👋',
    noAlerts: 'வானிலை எச்சரிக்கை இல்லை. அனுப்புவதற்கு பாதுகாப்பானது.',
    selectMaterial: 'பொருளைத் தேர்ந்தெடு',
    proceed: 'கட்டணத்திற்கு தொடரவும்',
    payNow: '🔒 கட்டணம் செலுத்து',
    back: '← பின்',
    skip: 'தவிர்',
    next: 'அடுத்து →',
    chat: 'அரட்டை',
    scanQR: 'QR குறியீட்டை ஸ்கேன் செய்',
    offline: 'நீங்கள் ஆஃப்லைனில் இருக்கிறீர்கள்',
    offlineSub: 'தற்காலிக தரவு காட்டப்படுகிறது',
    adminPanel: 'நிர்வாக பலகம்',
    
    // Profile menu items
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    companyDetails: 'நிறுவனத்தின் விவரங்கள்',
    kycDocs: 'KYC & வாகன ஆவணங்கள்',
    paymentMethods: 'கட்டண முறைகள்',
    notificationPrefs: 'அறிவிப்பு விருப்பங்கள்',
    helpSupport: 'உதவி & ஆதரவு',
    aboutApp: 'LogiRoute பற்றி',
    driverLabel: 'ஓட்டுநர்',
    companyLabel: 'நிறுவனம்',
    verifiedBadge: 'சரிபார்க்கப்பட்டது',
    pendingBadge: 'நிலுவையில் உள்ளது',
    editProfileSub: 'பெயர், புகைப்படம், தொடர்புத் தகவலைப் புதுப்பி',
    companyDetailsSub: 'ஜிஎஸ்டி, முகவரி, பதிவு',
    kycDocsSub: 'அதிகாரப்பூர்வ பான், ஆதார், வாகன பதிவு',
    paymentMethodsSub: 'UPI, வங்கி கணக்குகள்',
  },
  hi: {
    appName: 'LogiRoute',
    tagline: 'स्मार्ट लॉजिस्टिक्स ऑप्टिमाइज़र',
    getStarted: 'शुरू करें',
    login: 'लॉगिन',
    register: 'अकाउंट बनाएं',
    email: 'ईमेल / फोन',
    password: 'पासवर्ड',
    forgotPassword: 'पासवर्ड भूल गए?',
    welcome: 'वापसी पर स्वागत है 👋',
    loginSub: 'अपने अकाउंट में लॉगिन करें',
    dashboard: 'डैशबोर्ड',
    shipments: 'शिपमेंट',
    optimize: 'ऑप्टिमाइज़',
    analytics: 'एनालिटिक्स',
    profile: 'प्रोफ़ाइल',
    newShipment: 'नया शिपमेंट',
    activeShipments: 'सक्रिय शिपमेंट',
    trackLive: 'लाइव ट्रैक करें',
    bookTransport: 'ट्रांसपोर्ट बुक करें',
    payment: 'भुगतान',
    confirmed: 'बुकिंग कन्फर्म!',
    weather: 'मौसम',
    history: 'इतिहास',
    notifications: 'सूचनाएं',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    source: 'स्रोत शहर...',
    destination: 'गंतव्य शहर...',
    optimizeRoute: '⚡ रूट ऑप्टिमाइज़ करें',
    material: 'सामग्री',
    route: 'रूट',
    distance: 'दूरी',
    estTime: 'अनुमानित समय',
    transport: 'परिवहन',
    minCost: 'न्यूनतम लागत',
    viewMap: '🗺 मैप देखें',
    compareAll: '📊 सभी लागत तुलना करें',
    bookThis: '✅ यह ट्रांसपोर्ट बुक करें',
    driver: 'ड्राइवर',
    earnings: 'कमाई',
    myTrips: 'मेरी यात्राएं',
    jobs: 'उपलब्ध काम',
    vehicle: 'वाहन स्थिति',
    goodMorning: 'सुप्रभात 👋',
    noAlerts: 'कोई मौसम चेतावनी नहीं। भेजना सुरक्षित है।',
    selectMaterial: 'सामग्री चुनें',
    proceed: 'भुगतान के लिए आगे बढ़ें',
    payNow: '🔒 भुगतान करें',
    back: '← वापस',
    skip: 'छोड़ें',
    next: 'अगला →',
    chat: 'चैट',
    scanQR: 'QR कोड स्कैन करें',
    offline: 'आप ऑफलाइन हैं',
    offlineSub: 'कैश्ड डेटा दिखाया जा रहा है',
    adminPanel: 'एडमिन पैनल',
    
    // Profile menu items
    editProfile: 'प्रोफ़ाइल संपादित करें',
    companyDetails: 'कंपनी का विवरण',
    kycDocs: 'केवाईसी और वाहन दस्तावेज',
    paymentMethods: 'भुगतान के तरीके',
    notificationPrefs: 'अधिसूचना प्राथमिकताएं',
    helpSupport: 'सहायता और समर्थन',
    aboutApp: 'LogiRoute के बारे में',
    driverLabel: 'ड्राइवर',
    companyLabel: 'कंपनी',
    verifiedBadge: 'सत्यापित',
    pendingBadge: 'लंबित',
    editProfileSub: 'नाम, फोटो, संपर्क अपडेट करें',
    companyDetailsSub: 'जीएसटी, पता, पंजीकरण',
    kycDocsSub: 'आधिकारिक पैन, आधार, वाहन आरसी',
    paymentMethodsSub: 'यूपीआई, बैंक खाते',
  },
  te: {
    appName: 'LogiRoute',
    tagline: 'స్మార్ట్ లాజిస్టికస్ ఆప్టిమైజర్',
    getStarted: 'ప్రారంభించండి',
    login: 'లాగిన్',
    register: 'ఖాతా సృష్టించండి',
    email: 'ఈమెయిల్ / ఫోన్',
    password: 'పాస్‌వర్డ్',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    welcome: 'స్వాగతం 👋',
    loginSub: 'మీ ఖాతాకు లాగిన్ అవ్వండి',
    dashboard: 'డాష్‌బోర్డ్',
    shipments: 'రవాణా జాబితా',
    optimize: 'ఆప్టిమైజ్',
    analytics: 'విశ్లేషణలు',
    profile: 'ప్రొఫైల్',
    newShipment: 'కొತ್ತ రవాణా',
    activeShipments: 'సక్రియ రవాణా',
    trackLive: 'లైవ్ ట్రాక్',
    bookTransport: 'రవాణా బుకింగ్',
    payment: 'చెల్లింపు',
    confirmed: 'బుకింగ్ ఖరారైంది!',
    weather: 'వాతావరణం',
    history: 'చరిత్ర',
    notifications: 'నోటిఫికేషన్లు',
    settings: 'సెట్టింగులు',
    logout: 'లాగౌట్',
    source: 'బయలుదేరే నగరం...',
    destination: 'చేరుకునే నగరం...',
    optimizeRoute: '⚡ రూట్ ఆప్టిమైజ్ చేయి',
    material: 'సరుకు రకం',
    route: 'మార్గం',
    distance: 'దూరం',
    estTime: 'సమయం',
    transport: 'రవాణా మార్గం',
    minCost: 'కనీస ఖర్చు',
    viewMap: '🗺 మ్యాప్ చూడండి',
    compareAll: '📊 ఖర్చులను సరిపోల్చండి',
    bookThis: '✅ ఈ రవాణాని బుక్ చేయి',
    driver: 'డ్రైవర్',
    earnings: 'సంపాదన',
    myTrips: 'నా ప్రయాణాలు',
    jobs: 'జాబ్స్',
    vehicle: 'వాహన స్థితి',
    goodMorning: 'శుభోదయం 👋',
    noAlerts: 'వాతావరణ హెಚ್ಚరికలు లేవు. సురక్షಿತం.',
    selectMaterial: 'సరుకును ఎంచుకోండి',
    proceed: 'చెల్లింపునకు వెళ్లండి',
    payNow: '🔒 చెల్లించండి',
    back: '← వెనక్కి',
    skip: 'వదిలేయండి',
    next: 'తరువాత →',
    chat: 'చాట్',
    scanQR: 'QR కోడ్ స్కాన్ చేయి',
    offline: 'మీరు ఆఫ్ లైన్ లో ఉన్నారు',
    offlineSub: 'పాత సమాచారం చూపబడుతోంది',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    
    // Profile menu items
    editProfile: 'ప్రొఫైల్ సవరించండి',
    companyDetails: 'కంపెనీ వివరాలు',
    kycDocs: 'KYC & వాహన పత్రాలు',
    paymentMethods: 'చెల్లింపు పద్ధతులు',
    notificationPrefs: 'నోటిఫికేషన్ ప్రాధాన్యతలు',
    helpSupport: 'సహాయం & మద్దతు',
    aboutApp: 'LogiRoute గురించి',
    driverLabel: 'డ్రైవర్',
    companyLabel: 'కంపెనీ',
    verifiedBadge: 'ధృవీకరించబడింది',
    pendingBadge: 'పెండింగ్',
    editProfileSub: 'పేరు, ఫోటో, పరిచయం అప్‌డేట్ చేయండి',
    companyDetailsSub: 'GST, చిరునామా, రిజిస్ట్రేషన్',
    kycDocsSub: 'అధికారిక పాన్, ఆధార్, వాహన ఆర్సి',
    paymentMethodsSub: 'UPI, బ్యాంక్ ఖాతాలు',
  },
  kn: {
    appName: 'LogiRoute',
    tagline: 'ಸ್ಮಾರ್ಟ್ ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಆಪ್ಟಿಮೈಜರ್',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    login: 'ಲಾಗಿನ್',
    register: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    email: 'ಇಮೇಲ್ / ಫೋನ್ ಸಂಖ್ಯೆ',
    password: 'ಪಾಸ್ವರ್ಡ್',
    forgotPassword: 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?',
    welcome: 'ಸ್ವಾಗತ 👋',
    loginSub: 'ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    shipments: 'ಸಾಗಣೆಗಳು',
    optimize: 'ಆಪ್ಟಿಮೈಜ್',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    newShipment: 'ಹೊಸ ಸಾಗಣೆ',
    activeShipments: 'ಸಕ್ರಿಯ ಸಾಗಣೆಗಳು',
    trackLive: 'ಲೈವ್ ಟ್ರ್ಯಾಕ್',
    bookTransport: 'ಬುಕಿಂಗ್ ಮಾಡಿ',
    payment: 'ಪಾವತಿ',
    confirmed: 'ಬುಕಿಂಗ್ ಖಚಿತಪಟ್ಟಿದೆ!',
    weather: 'ಹವಾಮಾನ',
    history: 'ಇತಿಹಾಸ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    logout: 'ಲಾಗ್ಔಟ್',
    source: 'ಹೊರಡುವ ಸ್ಥಳ...',
    destination: 'ತಲುಪುವ ಸ್ಥಳ...',
    optimizeRoute: '⚡ ಮಾರ್ಗ ಆಪ್ಟಿಮೈಜ್ ಮಾಡಿ',
    material: 'ಸರಕು ಪ್ರಕಾರ',
    route: 'ಮಾರ್ಗ',
    distance: 'ದೂರ',
    estTime: 'ಅಂದಾಜು ಸಮಯ',
    transport: 'ಸಾರಿಗೆ',
    minCost: 'ಕನಿಷ್ಠ ವೆಚ್ಚ',
    viewMap: '🗺 ನಕ್ಷೆ ವೀಕ್ಷಿಸಿ',
    compareAll: '📊 ವೆಚ್ಚಗಳನ್ನು ಹೋಲಿಸಿ',
    bookThis: '✅ ಸಾರಿಗೆ ಕಾಯ್ದಿರಿಸಿ',
    driver: 'ಚಾಲಕ',
    earnings: 'ಗಳಿಕೆ',
    myTrips: 'ನನ್ನ ಪ್ರವಾಸಗಳು',
    jobs: 'ಲಭ್ಯವಿರುವ ಕೆಲಸಗಳು',
    vehicle: 'ವಾಹನದ ವಿವರ',
    goodMorning: 'ಶುಭ ಮುಂಜಾನೆ 👋',
    noAlerts: 'ಯಾವುದೇ ಹವಾಮಾನ ಮುನ್ನೆಚ್ಚರಿಕೆ ಇಲ್ಲ.',
    selectMaterial: 'ಸರಕು ಆಯ್ಕೆ ಮಾಡಿ',
    proceed: 'ಪಾವತಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    payNow: '🔒 ಪಾವತಿಸಿ',
    back: '← ಹಿಂದೆ',
    skip: 'ವಜಾಗೊಳಿಸಿ',
    next: 'ಮುಂದೆ →',
    chat: 'ಚಾಟ್',
    scanQR: 'QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    offline: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ',
    offlineSub: 'ಹಳೆಯ ಡೇಟಾ ತೋರಿಸಲಾಗುತ್ತಿದೆ',
    adminPanel: 'ನಿರ್ವಾಹಕ ಫಲಕ',
    
    // Profile menu items
    editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    companyDetails: 'ಕಂಪನಿ ವಿವರಗಳು',
    kycDocs: 'KYC ಮತ್ತು ವಾಹನ ದಾಖಲೆಗಳು',
    paymentMethods: 'ಪಾವತಿ ವಿಧಾನಗಳು',
    notificationPrefs: 'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು',
    helpSupport: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    aboutApp: 'LogiRoute ಬಗ್ಗೆ',
    driverLabel: 'ಚಾಲಕ',
    companyLabel: 'ಕಂಪನಿ',
    verifiedBadge: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    pendingBadge: 'ಬಾಕಿ ಉಳಿದಿದೆ',
    editProfileSub: 'ಹೆಸರು, ಫೋಟೋ, ಸಂಪರ್ಕ ನವೀಕರಿಸಿ',
    companyDetailsSub: 'GST, ವಿಳಾಸ, ನೋಂದಣಿ',
    kycDocsSub: 'ಅಧಿಕೃತ ಪ್ಯಾನ್, ಆಧಾರ್, ವಾಹನ ಆರ್ಸಿ',
    paymentMethodsSub: 'UPI, ಬ್ಯಾಂಕ್ ಖಾತೆಗಳು',
  }
};

const LangContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  useEffect(() => {
    AsyncStorage.getItem('logiroute_user_profile').then(raw => {
      if (raw) {
        const parsed = JSON.parse(raw);
        if (parsed.language) setLang(parsed.language);
      }
    });
  }, []);

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  return (
    <LangContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

// Language Selector Component
import { View, TouchableOpacity, Text, StyleSheet } from 'react-native';

export function LanguageSelector() {
  const { lang, setLang } = useLang();
  const options = [
    { id: 'en', label: 'EN', flag: '🇬🇧', name: 'English' },
    { id: 'ta', label: 'தமிழ்', flag: '🇮🇳', name: 'Tamil' },
    { id: 'hi', label: 'हिंदी', flag: '🇮🇳', name: 'Hindi' },
    { id: 'te', label: 'తెలుగు', flag: '🇮🇳', name: 'Telugu' },
    { id: 'kn', label: 'ಕನ್ನಡ', flag: '🇮🇳', name: 'Kannada' }
  ];
  return (
    <View style={ls.row}>
      {options.map(opt => (
        <TouchableOpacity key={opt.id} onPress={() => {
          setLang(opt.id);
          AsyncStorage.getItem('logiroute_user_profile').then(raw => {
            const current = raw ? JSON.parse(raw) : {};
            AsyncStorage.setItem('logiroute_user_profile', JSON.stringify({ ...current, language: opt.id }));
          });
        }} style={[ls.btn, lang === opt.id && ls.btnActive]}>
          <Text style={ls.flag}>{opt.flag}</Text>
          <Text style={[ls.label, lang === opt.id && ls.labelActive]}>{opt.label}</Text>
        </TouchableOpacity>
      ))}
    </View>
  );
}

const ls = StyleSheet.create({
  row: { flexDirection: 'row', gap: 8 },
  btn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#1C2030', borderWidth: 1, borderColor: '#2E3450', borderRadius: 999, paddingVertical: 7, paddingHorizontal: 14 },
  btnActive: { borderColor: '#F5C842', backgroundColor: 'rgba(245,200,66,0.15)' },
  flag: { fontSize: 14 },
  label: { fontSize: 12, color: '#8892A4', fontWeight: '600' },
  labelActive: { color: '#F5C842' },
});
